# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nvleonovich_homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SDWebImage'
pod 'RealmSwift'
pod 'Firebase/Auth'	
pod 'Firebase/Firestore'
  # Pods for nvleonovich_homework

end
